name: SARS2-mut-fitness
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - biopython=1.79
  - black-jupyter
  - entrez-direct=16.2
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-nb
  - git-lfs
  - jupyter_contrib_nbextensions
  - jupyterlab
  - pandas=1.4
  - papermill=2.3.4
  - pip
  - python=3.9
  - scikit-learn=1.1.1
  - snakemake=7.18.2
  - usher=0.5.6
  - pip:
    - git+https://github.com/altair-viz/altair@0217b2e73703d3b7b529b73b4dec9c17e7fb09bb
    - git+https://github.com/jbloomlab/polyclonal/@3.0
